/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.example.sca.ui.cloud.encryptalgorithm.trabe.policyparser;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(PolicyParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6f9833367981a778c9f6de7a6fcb6a9 (do not edit this line) */
