/* Generated By:JavaCC: Do not edit this line. PolicyParserTreeConstants.java Version 6.1_2 */
package com.example.sca.ui.cloud.encryptalgorithm.trabe.policyparser;

public interface PolicyParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSION = 2;
  public int JJTOF = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTNUMERICALATTRIBUTE = 5;
  public int JJTGEOHASHATTRIBUTE = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Expression",
    "Of",
    "Attribute",
    "NumericalAttribute",
    "GeoHashAttribute",
  };
}
/* JavaCC - OriginalChecksum=05d05fcd6a13e21f9894f0e08e8ad883 (do not edit this line) */
